apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: lab2
  labels:
    app: web
  annotations:
    owner: "nour"
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: web
      tier: frontend
  template:
    metadata:
      labels:
        app: web
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: nginx:doesnotexist
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 32Mi
          limits:
            cpu: 100m
            memory: 64Mi
